#Set the server type (mainlobby/otherlobby/game)
servertype: mainlobby

#Set the default spawn point
spawn:
  x: 0
  y: 0
  z: 0
  pitch: -180
  yaw: 0

#Set the MoTD
motd:
  - line1
  - line2
  - line3

#Minumum time in-between chats (in seconds):
chattime: 10

#Manage the database settings:
database:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "admin"
  password: "1234"