name: MindcrackHelper
version: 0.5
description: A Bukkit plugin for the Mindcrack Marathon designed to implement base functionality.
author: Matthew Salsamendi

main: com.mcprohosting.plugins.mindcrack.Mindcrack
database: false

depend: [LilyPad-Connect]

commands:
   spawn:
     description: Teleport the player to the spawn location.
     usage: /<command>
     aliases: []
   givepoints:
     description: Give points to a player.
     usage: /<command> <player> <amount>
permissions:
   mindcrack.*:
     description: Allows all Mindcrack related commands
     children:
       mindcrack.changeblocks: true
   mindcrack.changeblocks:
     description: Allows the user to change blocks on the server
     default: op
   mindcrack.givepoints:
     description: Allows the user to give players points using the /givepoints command.
     default: op